version: '3.8'

services:
  auth_service:
    build:
      context: ./auth_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./auth.db
      - GOOGLE_CLIENT_ID=422582982715-i1nckd6lehufls1vihouaag0uflvni95.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    volumes:
      - ./auth_service:/usr/src/app
      - ./auth_service/app/templates:/app/templates
    networks:
      - ecommerce-network

  product_service:
    build:
      context: ./product_service
    ports:
      - "8001:8000"  # Product service is exposed on port 8001
    environment:
      - DATABASE_URL=sqlite:///./product.db
    volumes:
      - ./product_service:/app
      - ./product_service/uploaded_images:/app/uploaded_images
      - ./templates:/app/templates
    networks:
      - ecommerce-network

  seller_service:
    build:
      context: ./seller_service
    ports:
      - "8002:8000"  # Seller service will be exposed on port 8002
    environment:
      - DATABASE_URL=sqlite:///./seller.db
    volumes:
      - ./seller_service:/app
    networks:
      - ecommerce-network

  cart_service:
    build:
      context: ./cart_service
    ports:
      - "8003:8000"  # Cart service will be exposed on port 8003
    environment:
      - DATABASE_URL=sqlite:///./cart.db
    volumes:
      - ./cart_service:/app
    networks:
      - ecommerce-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapipassword
      POSTGRES_DB: ecommerce_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./templates:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth_service
      - product_service
      - seller_service
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge