table CreditCard
	lineageTag: a7b7c385-ef6e-45b4-a362-5f32c27d1e5d

	column CreditID
		dataType: int64
		formatString: 0
		lineageTag: 07be2639-a1a4-4b11-b5a6-66f74e437665
		summarizeBy: none
		sourceColumn: CreditID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: b771146d-dc38-4bc6-9016-c7546e034e9d
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition CreditCard = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Bihaag Nepaul\Downloads\YT-Banking-Domain\CreditCard.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"CreditID", Int64.Type}, {"Category", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

