table Gender
	lineageTag: 508a7bfb-e5ba-4cd6-9fc0-e7a80df9e6ae

	column GenderID
		dataType: int64
		formatString: 0
		lineageTag: 73e774fd-c0ab-45e6-b0e5-537b046c76f9
		summarizeBy: none
		sourceColumn: GenderID

		annotation SummarizationSetBy = Automatic

	column GenderCategory
		dataType: string
		lineageTag: c7d64c03-b9a5-435f-b846-33444940a214
		summarizeBy: none
		sourceColumn: GenderCategory

		annotation SummarizationSetBy = Automatic

	partition Gender = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Bihaag Nepaul\Downloads\YT-Banking-Domain\Gender.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"GenderID", Int64.Type}, {"GenderCategory", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

