table '4-5-4 Calendar'
	lineageTag: 94e77454-9f68-47ef-b086-8c08a1dd9265

	measure 'Lost Revenue (SUMMARIZE Table)' =
			
			SUMX(
			    'Unsold Pastries',
			    [Food Unsold (SUMMARIZE TABLE)] * 'Unsold Pastries'[current_retail_price]
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 93152a64-bc94-4352-ab57-a342d7c6b8b7

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6b4a5b5a-c0d5-41d2-a016-b9ee25e2a29d
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 05c09cde-2847-4651-90c5-8ebca594e798
			defaultHierarchy: LocalDateTable_d7b91c60-11f1-4b7e-b0b2-1f6b61aa4272.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: a47b2505-f673-4139-b1b1-3e242c0666dc
		summarizeBy: sum
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalQuarter
		dataType: int64
		formatString: 0
		lineageTag: c1b1a39e-3649-479b-95b6-695bb3416a04
		summarizeBy: sum
		sourceColumn: FiscalQuarter

		annotation SummarizationSetBy = Automatic

	column FiscalMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: a39b5e33-da68-4483-8e7b-31731f91b9ec
		summarizeBy: sum
		sourceColumn: FiscalMonthNumber

		annotation SummarizationSetBy = Automatic

	column FiscalMonthOfQuarter
		dataType: int64
		formatString: 0
		lineageTag: ee402a92-52d3-46e1-aa0d-9d9a9c229914
		summarizeBy: sum
		sourceColumn: FiscalMonthOfQuarter

		annotation SummarizationSetBy = Automatic

	column FiscalWeekOfYear
		dataType: int64
		formatString: 0
		lineageTag: 1c32ab02-ae01-4ff0-b03a-87e9cbe696fc
		summarizeBy: sum
		sourceColumn: FiscalWeekOfYear

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: 46ee783c-2fbf-4e38-ae27-da64fe8c2545
		summarizeBy: sum
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column FiscalMonthName
		dataType: string
		lineageTag: cd99c087-5f08-43d6-b1c3-6d002673f76f
		summarizeBy: none
		sourceColumn: FiscalMonthName

		annotation SummarizationSetBy = Automatic

	column FiscalMonthYear
		dataType: dateTime
		formatString: Long Date
		lineageTag: bbb856a7-3822-42b0-b557-105bef451c71
		summarizeBy: none
		sourceColumn: FiscalMonthYear

		variation Variation
			isDefault
			relationship: ef339c1b-648f-4d12-b6b0-c7d9048fc117
			defaultHierarchy: LocalDateTable_b30312ab-b70f-4406-be5b-2e2f5bfa49e8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FiscalQuarterYear
		dataType: int64
		formatString: 0
		lineageTag: a550bda4-16d7-47a7-ad6d-f4ba0cec267a
		summarizeBy: sum
		sourceColumn: FiscalQuarterYear

		annotation SummarizationSetBy = Automatic

	column DayOfMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 149adec4-7a2a-4b52-b401-0971ee0791aa
		summarizeBy: sum
		sourceColumn: DayOfMonthNumber

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: b3fcf4ee-de24-47bd-8fcc-4b0ffa4937e9
		summarizeBy: none
		sourceColumn: DayName

		annotation SummarizationSetBy = Automatic

	partition '4-5-4 Calendar' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Bihaag Nepaul\Downloads\Dax Udemy Files\Advanced DAX Data Files\4-5-4 Calendar.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"FiscalYear", Int64.Type}, {"FiscalQuarter", Int64.Type}, {"FiscalMonthNumber", Int64.Type}, {"FiscalMonthOfQuarter", Int64.Type}, {"FiscalWeekOfYear", Int64.Type}, {"DayOfWeek", Int64.Type}, {"FiscalMonthName", type text}, {"FiscalMonthYear", type date}, {"FiscalQuarterYear", Int64.Type}, {"DayOfMonthNumber", Int64.Type}, {"DayName", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

