table Categories
	lineageTag: 538a9b8d-8465-4620-a1ac-997dbf5db04b

	measure 'Prev Qtr' = CALCULATE([Total Rev Measure],PREVIOUSQUARTER(DateMaster[Date]))
		lineageTag: 15d98d45-8854-4f39-9596-f2f94932348b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Rev Measure' = SUM(Sales[Total Revenue])
		lineageTag: 921db533-0585-41c8-a970-f5af92172c52

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QoQ Growth' = ([Total Rev Measure]  - [Prev Qtr]) / [Prev Qtr]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2d48c808-e4ce-4d5b-a310-eeeb68d942ec

	measure 'MoM Growth' = ([Tot Profit (Measure)] - [Prev Month Profit]) / [Prev Month Profit]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bd55cfc6-da96-4908-8774-917e2b585b36

	column CategoryKey
		dataType: int64
		formatString: 0
		lineageTag: f40f718e-eae8-49b2-a978-87b6c41abb37
		summarizeBy: none
		sourceColumn: CategoryKey

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 7d8719fa-5265-4951-a53b-4dca04d7eb95
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition Categories = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Bihaag Nepaul\Downloads\YT-Datasets\Dimensions\Categories.xlsx"), null, true),
				    Categories_Sheet = Source{[Item="Categories",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Categories_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CategoryKey", Int64.Type}, {"Category", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

