table Sales
	lineageTag: a13e0593-458b-454f-9c33-2d5c34246f95

	column 'Source.Name'
		dataType: string
		lineageTag: 7a73c503-51af-4af6-ac6a-ca306e048612
		summarizeBy: none
		sourceColumn: Source.Name

		annotation SummarizationSetBy = Automatic

	column fSalesPrimaryKey
		dataType: int64
		formatString: 0
		lineageTag: 9da6ff69-11d1-4cca-9ae5-244b110b984e
		summarizeBy: count
		sourceColumn: fSalesPrimaryKey

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: f4c4f1e7-af56-46b1-8244-78020a1ca3e9
		summarizeBy: count
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column SalesRepID
		dataType: int64
		formatString: 0
		lineageTag: 6ca423c4-01e1-42a3-bf16-d852b6f8cac0
		summarizeBy: count
		sourceColumn: SalesRepID

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: f5d62622-0af5-4bdf-8228-a0fbfadda9cb
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 83fa262d-1d2a-4661-8472-ce5e1b68ccd7
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Units
		dataType: int64
		formatString: 0
		lineageTag: ee5e6a71-2ba7-4477-b738-390e51d74af2
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

	column PercentOfStandardCost
		dataType: string
		lineageTag: f63cd561-d0ee-4bfe-a890-0609677f300b
		summarizeBy: none
		sourceColumn: PercentOfStandardCost

		annotation SummarizationSetBy = Automatic

	column RevenueDiscount
		dataType: string
		lineageTag: f560fd07-c6b2-47a3-a650-4cabdb01bb66
		summarizeBy: none
		sourceColumn: RevenueDiscount

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\Bihaag Nepaul\Downloads\YT-Datasets\Sales"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"fSalesPrimaryKey", Int64.Type}, {"ProductID", Int64.Type}, {"SalesRepID", Int64.Type}, {"Location", type text}, {"Date", type date}, {"Units", Int64.Type}, {"PercentOfStandardCost", type text}, {"RevenueDiscount", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

