table Sales
	lineageTag: ac52cd88-1e20-4cfd-b2c6-ca6368f463a4

	column fSalesPrimaryKey
		dataType: int64
		formatString: 0
		lineageTag: 63cb781a-b231-4230-b277-376fa48885b3
		summarizeBy: count
		sourceColumn: fSalesPrimaryKey

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: bb59606a-59ee-485a-8811-4db8a724bbeb
		summarizeBy: count
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column SalesRepID
		dataType: int64
		formatString: 0
		lineageTag: c88581af-31de-452d-a92f-110731359851
		summarizeBy: count
		sourceColumn: SalesRepID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4231e299-40bf-4714-afbe-80aece2938a7
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Units
		dataType: int64
		formatString: 0
		lineageTag: 852c96f1-f874-40a8-b427-bf05439448dd
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

	column PercentOfStandardCost
		dataType: double
		lineageTag: 07faa0c5-c170-4ed0-b084-6551978c59af
		summarizeBy: sum
		sourceColumn: PercentOfStandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RevenueDiscount
		dataType: double
		lineageTag: cf429b2d-d743-4c0f-8f28-a2e9118a5334
		summarizeBy: sum
		sourceColumn: RevenueDiscount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Country
		dataType: string
		lineageTag: 031fb124-3be1-4108-ab4e-0297dd9c96f0
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Town
		dataType: string
		lineageTag: 01221cb9-e526-415e-9320-fcf55a4b7a46
		summarizeBy: none
		sourceColumn: Town

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\Bihaag Nepaul\Downloads\YT-Datasets\Sales"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (3)", each #"Transform File (3)"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (3)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (3)", Table.ColumnNames(#"Transform File (3)"(#"Sample File (3)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"fSalesPrimaryKey", Int64.Type}, {"ProductID", Int64.Type}, {"SalesRepID", Int64.Type}, {"Location", type text}, {"Date", type date}, {"Units", Int64.Type}, {"PercentOfStandardCost", type number}, {"RevenueDiscount", type number}}),
				    #"Remove Source Details" = Table.RemoveColumns(#"Changed Type",{"Source.Name"}),
				    #"Splitted the location" = Table.SplitColumn(#"Remove Source Details", "Location", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {"Location.1", "Location.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Splitted the location",{{"Location.1", type text}, {"Location.2", type text}}),
				    #"Renamed Columns from location 1 to Country & location 2 to Town" = Table.RenameColumns(#"Changed Type1",{{"Location.1", "Country"}, {"Location.2", "Town"}})
				in
				    #"Renamed Columns from location 1 to Country & location 2 to Town"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

