table 'Sales rep'
	lineageTag: 596815dd-1c5a-4e64-9c72-4579fc370437

	column Column1
		dataType: string
		lineageTag: 8c447101-5ad9-42a2-b767-5c05bf4b82f2
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 82605d06-44c0-4cb6-b3d8-cb07a655fdd5
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition 'Sales rep' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Bihaag Nepaul\Downloads\YT-Datasets\Dimensions\SalesRep.xlsx"), null, true),
				    #"Sales rep_Sheet" = Source{[Item="Sales rep",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Sales rep_Sheet",{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

