table Sales
	lineageTag: ac52cd88-1e20-4cfd-b2c6-ca6368f463a4

	column 'Source.Name'
		dataType: string
		lineageTag: 0b11b19a-0945-46dc-a59e-49809f31b4b1
		summarizeBy: none
		sourceColumn: Source.Name

		annotation SummarizationSetBy = Automatic

	column fSalesPrimaryKey
		dataType: int64
		formatString: 0
		lineageTag: 63cb781a-b231-4230-b277-376fa48885b3
		summarizeBy: count
		sourceColumn: fSalesPrimaryKey

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: bb59606a-59ee-485a-8811-4db8a724bbeb
		summarizeBy: count
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column SalesRepID
		dataType: int64
		formatString: 0
		lineageTag: c88581af-31de-452d-a92f-110731359851
		summarizeBy: count
		sourceColumn: SalesRepID

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: e8fc1ca7-2ee0-4016-a4e8-14bafbacb8c2
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4231e299-40bf-4714-afbe-80aece2938a7
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Units
		dataType: int64
		formatString: 0
		lineageTag: 852c96f1-f874-40a8-b427-bf05439448dd
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

	column PercentOfStandardCost
		dataType: double
		lineageTag: 07faa0c5-c170-4ed0-b084-6551978c59af
		summarizeBy: sum
		sourceColumn: PercentOfStandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RevenueDiscount
		dataType: double
		lineageTag: cf429b2d-d743-4c0f-8f28-a2e9118a5334
		summarizeBy: sum
		sourceColumn: RevenueDiscount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sales = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\Bihaag Nepaul\Downloads\YT-Datasets\Sales"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (3)", each #"Transform File (3)"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (3)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (3)", Table.ColumnNames(#"Transform File (3)"(#"Sample File (3)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"fSalesPrimaryKey", Int64.Type}, {"ProductID", Int64.Type}, {"SalesRepID", Int64.Type}, {"Location", type text}, {"Date", type date}, {"Units", Int64.Type}, {"PercentOfStandardCost", type number}, {"RevenueDiscount", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

