table SharePointSales
	lineageTag: f0ae3e3d-48af-4112-9bc2-ff883a1bed03

	column fSalesPrimaryKey
		dataType: int64
		formatString: 0
		lineageTag: 9d9d0153-ca0a-4739-97a8-619aa5708b69
		summarizeBy: none
		sourceColumn: fSalesPrimaryKey

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 9573ccf6-3da8-49a5-9fd4-a8bd9d95be55
		summarizeBy: count
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column SalesRepID
		dataType: int64
		formatString: 0
		lineageTag: 8c5bcda6-a3b1-425d-b217-d90528dccc9c
		summarizeBy: count
		sourceColumn: SalesRepID

		annotation SummarizationSetBy = Automatic

	column 'Geography.GeoKey'
		dataType: int64
		formatString: 0
		lineageTag: dcfb152a-3ffc-419e-bfc5-c4dfcbc2c37c
		summarizeBy: count
		sourceColumn: Geography.GeoKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 199cb84a-2904-4861-98aa-9d242ab340bc
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Units
		dataType: int64
		formatString: 0
		lineageTag: eb4e9c55-fa03-4d74-88d0-760fdcfa49c4
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

	column PercentOfStandardCost
		dataType: double
		lineageTag: f781e736-8679-4044-af35-c11c695afaa1
		summarizeBy: sum
		sourceColumn: PercentOfStandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RevenueDiscount
		dataType: double
		lineageTag: 0c3dd0bb-47a3-4197-8226-c82f0e378193
		summarizeBy: sum
		sourceColumn: RevenueDiscount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Revenue' = SharePointSales[Units] * RELATED(ProductDetails[RetailPrice])
		dataType: double
		lineageTag: 427cacb1-863e-44e1-b36e-c041cb1eb5dd
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Cost' = SharePointSales[Units] * RELATED(ProductDetails[StandardCost])
		dataType: double
		lineageTag: 4a3c65b9-fedc-4f47-8ae4-ea0200d83309
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Gross Profit' = SharePointSales[Total Revenue] - SharePointSales[Total Cost]
		dataType: double
		lineageTag: 1eed6cd2-b5dc-40fa-a864-6c8fb0b69abf
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition SharePointSales = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://northerndata.sharepoint.com/sites/BihaagTestTeam/", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Folder Path] = SharePointSalesDEV)),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (3)", each #"Transform File (3)"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (3)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (3)", Table.ColumnNames(#"Transform File (3)"(#"Sample File (3)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"fSalesPrimaryKey", Int64.Type}, {"ProductID", Int64.Type}, {"SalesRepID", Int64.Type}, {"Location", type text}, {"Date", type date}, {"Units", Int64.Type}, {"PercentOfStandardCost", type number}, {"RevenueDiscount", type number}}),
				    #"Remove Source Details" = Table.RemoveColumns(#"Changed Type",{"Source.Name"}),
				    #"Splitted the location" = Table.SplitColumn(#"Remove Source Details", "Location", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {"Location.1", "Location.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Splitted the location",{{"Location.1", type text}, {"Location.2", type text}}),
				    #"Renamed Columns from location 1 to Country & location 2 to Town" = Table.RenameColumns(#"Changed Type1",{{"Location.1", "Country"}, {"Location.2", "Town"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns from location 1 to Country & location 2 to Town", {"Country", "Town"}, Geography, {"Country", "Town"}, "Geography", JoinKind.LeftOuter),
				    #"Expanded Geography" = Table.ExpandTableColumn(#"Merged Queries", "Geography", {"GeoKey"}, {"Geography.GeoKey"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded Geography",{"fSalesPrimaryKey", "ProductID", "SalesRepID", "Geography.GeoKey", "Country", "Town", "Date", "Units", "PercentOfStandardCost", "RevenueDiscount"}),
				    #"Removed redundant county and town and replaced with Geokey in sales" = Table.RemoveColumns(#"Reordered Columns",{"Country", "Town"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed redundant county and town and replaced with Geokey in sales", each true)
				in
				    #"Filtered Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

