table SharePointSales(DEV)
	lineageTag: f0ae3e3d-48af-4112-9bc2-ff883a1bed03

	column Name
		dataType: string
		lineageTag: a85b00ec-df79-45a9-a4bb-c1090657c857
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Extension
		dataType: string
		lineageTag: 1d5766ae-9360-420d-8808-c653bf4739b0
		summarizeBy: none
		sourceColumn: Extension

		annotation SummarizationSetBy = Automatic

	column 'Date accessed'
		dataType: dateTime
		formatString: General Date
		lineageTag: b0037f9c-3f42-4177-aa70-a2a92009c925
		summarizeBy: none
		sourceColumn: Date accessed

		annotation SummarizationSetBy = Automatic

	column 'Date modified'
		dataType: dateTime
		formatString: General Date
		lineageTag: 651cc34e-cd75-4bd1-bb27-a8f24e6dfa91
		summarizeBy: none
		sourceColumn: Date modified

		annotation SummarizationSetBy = Automatic

	column 'Date created'
		dataType: dateTime
		formatString: General Date
		lineageTag: 73cb29d6-83e2-4fcf-97ae-855f03662ad5
		summarizeBy: none
		sourceColumn: Date created

		annotation SummarizationSetBy = Automatic

	column 'Folder Path'
		dataType: string
		lineageTag: 58fb533e-41a1-4c4a-bc41-2be5f1c6b20d
		summarizeBy: none
		sourceColumn: Folder Path

		annotation SummarizationSetBy = Automatic

	partition SharePointSales(DEV) = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://northerndata.sharepoint.com/sites/BihaagTestTeam/", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Folder Path] = "https://northerndata.sharepoint.com/sites/BihaagTestTeam/Shared Documents/General/YT-KSR Sales(Dev Data)/Sales/"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

