table Clients

	column Client_SK
		dataType: string
		summarizeBy: none
		sourceColumn: Client_SK

		annotation SummarizationSetBy = Automatic

	column ClientID
		dataType: int64
		formatString: 0
		summarizeBy: count
		sourceColumn: ClientID

		annotation SummarizationSetBy = Automatic

	column ClientName
		dataType: string
		summarizeBy: none
		sourceColumn: ClientName

		annotation SummarizationSetBy = Automatic

	column ClientProjName
		dataType: string
		summarizeBy: none
		sourceColumn: ClientProjName

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	partition Clients = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Bihaag Nepaul\Desktop\SSISDest\Client_DIM.xlsx"), null, true),
				    Clients_Sheet = Source{[Item="Clients",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Clients_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Client_SK", type text}, {"ClientID", Int64.Type}, {"ClientName", type text}, {"ClientProjName", type text}, {"Active", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

