table Cleaned_Timesheet

	column TimeSheetID
		dataType: int64
		formatString: 0
		summarizeBy: count
		sourceColumn: TimeSheetID

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Month
		dataType: string
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column DayofWeek
		dataType: string
		summarizeBy: none
		sourceColumn: DayofWeek

		annotation SummarizationSetBy = Automatic

	column Consultant
		dataType: string
		summarizeBy: none
		sourceColumn: Consultant

		annotation SummarizationSetBy = Automatic

	column Client
		dataType: string
		summarizeBy: none
		sourceColumn: Client

		annotation SummarizationSetBy = Automatic

	column ClientProjectName
		dataType: string
		summarizeBy: none
		sourceColumn: ClientProjectName

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column BillableorNonBillable
		dataType: string
		summarizeBy: none
		sourceColumn: BillableorNonBillable

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: string
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	column TotalHours
		dataType: dateTime
		formatString: Long Time
		summarizeBy: none
		sourceColumn: TotalHours

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column StartTime
		dataType: dateTime
		formatString: Long Time
		summarizeBy: none
		sourceColumn: StartTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column EndTime
		dataType: dateTime
		formatString: Long Time
		summarizeBy: none
		sourceColumn: EndTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition Cleaned_Timesheet = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Bihaag Nepaul\Desktop\SSISDest\Cleaned_Timesheet.txt"),[Delimiter=";", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"TimeSheetID", Int64.Type}, {"Date", type date}, {"Month", type text}, {"DayofWeek", type text}, {"Consultant", type text}, {"Client", type text}, {"ClientProjectName", type text}, {"Description", type text}, {"BillableorNonBillable", type text}, {"Comments", type text}, {"TotalHours", type time}, {"StartTime", type time}, {"EndTime", type time}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"TimeSheetID"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Errors", each [TimeSheetID] <> null and [TimeSheetID] <> ""),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows","Internal Sambe","Internal - SAMBE",Replacer.ReplaceText,{"Client"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Replaced Value", each ([Client] = "Internal - SAMBE") and ([BillableorNonBillable] = "Non-Billable")),
				    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows1", each [TotalHours] <> null and [TotalHours] <> ""),
				    #"Filtered Rows3" = Table.SelectRows(#"Filtered Rows2", each ([StartTime] <> null and [StartTime] <> "") and ([Consultant] <> "" and [Consultant] <> "Example"))
				in
				    #"Filtered Rows3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

