name: Deployment

on:
  push:
    branches: [ main ]

env:
  PROFILE: Files
  ENVIRONMENT: PROD

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: PROD
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: pbi-tools deploy
        run: /app/pbi-tools/pbi-tools.core deploy "./PowerBI DevOps/.pbixproj.json" "$PROFILE" "$ENVIRONMENT"
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
