name: Deployment

on:
  push:
    branches: [ main ]

env:
  PROFILE: Files
  ENVIRONMENT: PROD

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: PROD
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Debug info
        run: |
          echo "Current directory contents:"
          ls -R .
          echo "Listing PowerBI DevOps directory:"
          ls -R ./PowerBI\ DevOps
          echo "Environment variables:"
          env

      - name: List PowerBI DevOps directory
        run: ls -R ./PowerBI\ DevOps  # Ensure this directory and file exist

      - name: pbi-tools deploy
        run: /app/pbi-tools/pbi-tools.core deploy "./PowerBI DevOps/Sambe Timesheet Analysis.pbix" "$PROFILE" "$ENVIRONMENT"
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
