name: Deployment

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

env:
  PROFILE: report  # Ensure this matches the deployment name in .pbixproj.json
  ENVIRONMENT: PROD

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: PROD
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      # Debug step to list files in the PowerBI DevOps directory
      - name: List files in PowerBI DevOps directory
        run: ls -R ./PowerBI\ DevOps

      # Deploy Power BI report
      - name: Deploy Power BI report
        run: /app/pbi-tools/pbi-tools.core deploy "./PowerBI DevOps/Sambe Timesheet Analysis.pbix" "$PROFILE" "$ENVIRONMENT"
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}

