name: Deployment

on:
  push:
    branches: [ main ]

env:
  PROFILE: Files
  ENVIRONMENT: PROD

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: PROD
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Verify pbixproj.json path
        run: |
          if [ -f "./Bihaag_Nepaul/PowerBI DevOps/.pbixproj.json" ]; then
            echo "Found .pbixproj.json"
          else
            echo "Did not find .pbixproj.json"
            exit 1
          fi

      - name: pbi-tools deploy
        run: /app/pbi-tools/pbi-tools.core deploy "./Bihaag_Nepaul/PowerBI DevOps/.pbixproj.json" "$PROFILE" "$ENVIRONMENT"
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
