name: Deploy SSIS Package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQL Server tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          sudo apt-get install -y --no-install-recommends msodbcsql17
          
      - name: Deploy SSIS package
        env:
          SERVER_NAME: '0.tcp.eu.ngrok.io,12490'
          SQL_USER: 'AutomationUser'
          SQL_PASSWORD: 'MyP@ssw0rd2022@BEEBOI@PASSWORDff'
          PACKAGE_PATH: 'DatabaseAdministration/SSIS/UpdateData.dtsx'
          DEST_FOLDER: 'SSISDB/TestFolder'
        run: |
          echo "Deploying SSIS package..."
          sudo dtutil /FILE $PACKAGE_PATH /COPY SQL;"\${SERVER_NAME}";"/SSISDB/$DEST_FOLDER" /QUIET /CHECKPOINTING OFF /COPYF
