name: Deploy SSIS Package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQL Server tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          sudo apt-get install -y --no-install-recommends msodbcsql17

      - name: Deploy SSIS package
        run: |
          # Execute SQL command to deploy the SSIS package
          sqlcmd -S "0.tcp.eu.ngrok.io,12490" -U "AutomationUser" -P "MyP@ssw0rd2022@BEEBOI@PASSWORDff" -d SSISDB -Q "DECLARE @ProjectBinary AS varbinary(max); DECLARE @operation_id AS bigint; SET @ProjectBinary = (SELECT * FROM OPENROWSET(BULK '$GITHUB_WORKSPACE/DatabaseAdministration/SSIS/Ispac/SSIS-GraduateProject.ispac', SINGLE_BLOB) AS BinaryData); EXEC catalog.deploy_project @folder_name = 'SSIS-GraduateProject', @project_name = 'SSIS-GraduateProject', @Project_Stream = @ProjectBinary, @operation_id = @operation_id out"
