name: Deploy SSIS Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQL Server command-line tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev

      - name: Verify SQL Server command-line tools installation
        run: |
          sqlcmd -?
          bcp -?

      - name: Run PowerShell script
        uses: microsoft/powershell@v1
        with:
          pwsh: pwsh
          inlineScript: |
            Install-Module -Name SqlServer -Force -AllowClobber -Scope CurrentUser

      - name: Run SSIS Deployment script
        uses: microsoft/powershell@v1
        with:
          pwsh: pwsh
          inlineScript: |
            # Import the SqlServer module
            Import-Module SqlServer -Force

            # Set the SQL Server instance name and other variables
            $TargetServerName = "localhost,1433"
            $TargetFolderName = "SSIS-DataFlowAuditing"
            $ProjectFilePath = "DatabaseAdministration/SSIS/Ispac/SSIS-DataFlowAuditing.ispac"
            $ProjectName = "SSIS-DataFlowAuditing"

            # Create a connection to the SQL Server instance
            $sqlConnectionString = "Data Source=$TargetServerName;Initial Catalog=master;Integrated Security=SSPI;"
            $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $sqlConnectionString

            # Create the Integration Services object
            $integrationServices = New-Object "Microsoft.SqlServer.Management.IntegrationServices.IntegrationServices" $sqlConnection

            # Get the Integration Services catalog
            $catalog = $integrationServices.Catalogs["SSISDB"]

            # Create the target folder
            $folder = New-Object "Microsoft.SqlServer.Management.IntegrationServices.CatalogFolder" ($catalog, $TargetFolderName, "Folder description")
            $folder.Create()

            Write-Host "Deploying $ProjectName project ..."

            # Read the project file and deploy it
            $projectFile = [System.IO.File]::ReadAllBytes($ProjectFilePath)
            $folder.DeployProject($ProjectName, $projectFile)

            Write-Host "Done."
