name: Deploy SSIS Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download SQL Server installer
        run: |
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=866662" -OutFile SQLServer2019-x64-ENU.exe

      - name: Install SQL Server
        run: |
          Start-Process -Wait -FilePath "SQLServer2019-x64-ENU.exe" -ArgumentList "/ConfigurationFile=ConfigurationFile.ini /IAcceptSQLServerLicenseTerms"

      - name: Verify SQL Server installation
        run: |
          sqlcmd -S localhost -U SA -P '<YourStrongPassword>' -Q "SELECT @@VERSION"

      - name: Wait for MSSQL to start
        run: |
          echo "Waiting for MSSQL server to start..."
          Start-Sleep -Seconds 10  # Wait for 10 seconds

      - name: Run PowerShell script
        shell: pwsh
        run: |
          Install-Module -Name SQLServer -Scope CurrentUser -Force

      - name: Run PowerShell script
        shell: pwsh
        run: |
          ./SSISDeployment.ps1
